#!/usr/bin/env bash
#script for installing the nginx web_server
#also added redirection

WHERE="/etc/nginx/sites-available/default"
ADD="\\\tlocation \/redirect_me {\n\t\treturn 301 https://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
sed -i "30i $ADD" $WHERE
service nginx restart
