#!/usr/bin/env bash
#script for installing the nginx web_server
#also added redirection
#added the 404 page
WHERE="/etc/nginx/sites-available/default"
ADD="\\\tlocation \/redirect_me {\n\t\treturn 301 https://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
E404 = sudo sed -i "/TGUlwu4 permanent;/a\ \terror_page 404 /custom_404.html;"

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo service nginx start
sed -i "30i $ADD" $WHERE
sed -i "48i $E404" $WHERE
service nginx restart
