#!/usr/bin/env bash
# install load balancer with round robin
sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
yes enter | sudo add-apt-repository ppa:vbernat/haproxy-2.9
sudo apt-get update && apt-get upgrade -y
sudo apt-get install -y haproxy=2.9.\*
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
echo -e "\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend http_back\n\tbalance roundrobin\n\tserver 404-web-01 34.232.70.206:80 check\n\tserver 404-web-02 54.197.106.215:80 check" >> /etc/haproxy/haproxy.cfg
sudo service rsyslog restart
sudo service haproxy restart
