#!/usr/bin/env bash
# Pings an IP Address 5 times
# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Pings the IP 5 times

if [ "$#" -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

ip_address="$1"

ping -c 5 "$ip_address"
