#!/usr/bin/env bash
# Script for making localhost resolve to 127.0.0.2
# Also facebook.com resolve to 8.8.8.8

cp /etc/hosts ~/host_new
sed -i s/127.0.0.1/127.0.0.2/ ~/host_new
echo "8.8.8.8 facebook.com" >> ~/host_new
cp -f ~/host_new /etc/hosts
